import type { Trip } from "../types";

export const brasilNoviembre2026: Trip = {
  id: "brasil-noviembre-2026",
  title: "Brasil — Porto de Galinhas + Maragogi",
  subtitle: "Supermoon del 24-nov sobre Maragogi",
  startDate: "2026-11-15",
  endDate: "2026-11-29",
  origin: "Buenos Aires",
  destinations: ["Porto de Galinhas", "Maragogi"],
  travelers: 2,
  status: "planning",
  coastal: true,
  summary:
    "13 días en Brasil partidos en dos bases: Porto de Galinhas (urbano, vivo, jangadas) y Maragogi (tranquilo, con el Tour Galés en pico de marea baja durante la supermoon del 24-nov-2026).",

  flightCriteria: [
    { key: "tides", label: "Mareas", weight: 3 },
    { key: "direct", label: "Directo", weight: 2 },
    { key: "latam", label: "LATAM", weight: 1 },
  ],

  recommendedFlightId: 10,

  flightOptions: [
    {
      id: 1,
      outbound: { date: "2026-10-13", from: "AEP", to: "REC", airline: "JetSMART", depart: "04:39", arrive: "09:55", direct: true },
      inbound: { date: "2026-10-25", from: "REC", to: "AEP", airline: "JetSMART", depart: "11:00", arrive: "17:00", direct: true },
      days: 12,
      score: 1,
      comment: "Sin LATAM y mareas medias",
      criteria: { tides: "warning", direct: "yes", latam: "no" },
    },
    {
      id: 2,
      outbound: { date: "2026-10-14", from: "AEP", to: "REC", airline: "JetSMART", depart: "04:39", arrive: "09:55", direct: true },
      inbound: { date: "2026-10-25", from: "REC", to: "AEP", airline: "JetSMART", depart: "11:00", arrive: "17:00", direct: true },
      days: 11,
      score: 1,
      comment: "Sin LATAM y mareas medias",
      criteria: { tides: "warning", direct: "yes", latam: "no" },
    },
    {
      id: 3,
      outbound: { date: "2026-10-17", from: "AEP", to: "REC", airline: "JetSMART", depart: "04:39", arrive: "09:55", direct: true },
      inbound: { date: "2026-10-28", from: "REC", to: "AEP", airline: "JetSMART", depart: "11:00", arrive: "17:00", direct: true },
      days: 11,
      score: 2,
      comment: "Mareas y directo, pero sin LATAM",
      criteria: { tides: "yes", direct: "yes", latam: "no" },
    },
    {
      id: 4,
      outbound: { date: "2026-10-17", from: "AEP", to: "REC", airline: "JetSMART", depart: "04:39", arrive: "09:55", direct: true },
      inbound: { date: "2026-10-31", from: "REC", to: "EZE", airline: "LATAM", depart: "20:25", arrive: "01:55", direct: true },
      days: 14,
      score: 3,
      comment: "LATAM solo a la vuelta",
      criteria: { tides: "yes", direct: "yes", latam: "partial" },
    },
    {
      id: 5,
      outbound: { date: "2026-10-04", from: "EZE", to: "REC", airline: "LATAM", depart: "02:35", arrive: "07:45", direct: true },
      inbound: { date: "2026-10-17", from: "REC", to: "EZE", airline: "LATAM", depart: "20:15", arrive: "01:45", direct: true },
      days: 13,
      score: 4,
      comment: "LATAM directo, luna nueva 10-oct",
      criteria: { tides: "yes", direct: "yes", latam: "yes" },
      rank: 3,
    },
    {
      id: 6,
      outbound: { date: "2026-10-11", from: "EZE", to: "REC", airline: "LATAM", depart: "02:35", arrive: "07:45", direct: true },
      inbound: { date: "2026-10-24", from: "REC", to: "EZE", airline: "LATAM", depart: "20:15", arrive: "01:45", direct: true },
      days: 13,
      score: 3,
      comment: "LATAM puro pero mareas no son las mejores",
      criteria: { tides: "warning", direct: "yes", latam: "yes" },
    },
    {
      id: 7,
      outbound: { date: "2026-10-18", from: "EZE", to: "REC", airline: "LATAM", depart: "02:35", arrive: "07:45", direct: true },
      inbound: { date: "2026-10-31", from: "REC", to: "EZE", airline: "LATAM", depart: "20:25", arrive: "01:55", direct: true },
      days: 13,
      score: 4,
      comment: "LATAM directo, luna llena 26-oct",
      criteria: { tides: "yes", direct: "yes", latam: "yes" },
      rank: 2,
    },
    {
      id: 8,
      outbound: { date: "2026-10-04", from: "EZE", to: "REC", airline: "LATAM", depart: "02:35", arrive: "07:45", direct: true },
      inbound: { date: "2026-10-18", from: "REC", to: "AEP", airline: "LATAM", depart: "02:45", arrive: "10:30", direct: false, notes: "Escala en GRU" },
      days: 14,
      score: 2,
      comment: "LATAM pero pierde directo a la vuelta",
      criteria: { tides: "yes", direct: "partial", latam: "yes" },
    },
    {
      id: 9,
      outbound: { date: "2026-11-01", from: "AEP", to: "REC", airline: "JetSMART", depart: "04:39", arrive: "09:55", direct: true },
      inbound: { date: "2026-11-13", from: "REC", to: "AEP", airline: "JetSMART", depart: "11:00", arrive: "17:00", direct: true },
      days: 12,
      score: 2,
      comment: "Mareas y directo, pero sin LATAM",
      criteria: { tides: "yes", direct: "yes", latam: "no" },
    },
    {
      id: 10,
      outbound: { date: "2026-11-15", from: "EZE", to: "REC", airline: "LATAM", depart: "03:00", arrive: "08:10", direct: true },
      inbound: { date: "2026-11-28", from: "REC", to: "EZE", airline: "LATAM", depart: "20:25", arrive: "01:55", direct: true },
      days: 13,
      score: 5,
      isTop: true,
      rank: 1,
      comment: "🏆 PERFECTO — supermoon 24-nov, todo LATAM directo",
      criteria: { tides: "yes", direct: "yes", latam: "yes" },
    },
  ],

  moonPhases: [
    { date: "2026-10-10", phase: "new", tideQuality: "low", note: "Marés muy bajas" },
    { date: "2026-10-17", phase: "first-quarter", tideQuality: "medium", note: "Mareas moderadas" },
    { date: "2026-10-26", phase: "full", tideQuality: "low", note: "Marés muy bajas" },
    { date: "2026-11-01", phase: "last-quarter", tideQuality: "medium", note: "Mareas moderadas" },
    { date: "2026-11-08", phase: "new", tideQuality: "low", note: "Marés muy bajas" },
    { date: "2026-11-16", phase: "first-quarter", tideQuality: "medium", note: "Mareas moderadas" },
    { date: "2026-11-24", phase: "supermoon", tideQuality: "extreme", note: "Pico — supermoon, mareas excepcionalmente bajas" },
  ],

  tideWindows: [
    { label: "Luna nueva octubre", range: "8 – 13 oct", quality: "very-good" },
    { label: "Luna llena octubre", range: "24 – 29 oct", quality: "very-good" },
    { label: "Luna nueva noviembre", range: "6 – 12 nov", quality: "very-good" },
    { label: "Supermoon noviembre", range: "22 – 27 nov", quality: "exceptional", note: "Las mejores del año" },
  ],

  itinerary: [
    { dayNumber: 0, date: "2026-11-14", location: "Buenos Aires", title: "Preparativos y check-in", highlights: ["Check-in online", "Salida a Ezeiza ~00:30"], emoji: "🛫" },
    { dayNumber: 1, date: "2026-11-15", location: "Recife → Porto de Galinhas", title: "Llegada", highlights: ["Vuelo LATAM 03:00 → 08:10", "Transfer 1h a Porto", "Tarde de playa centro"], emoji: "🛬" },
    { dayNumber: 2, date: "2026-11-16", location: "Porto de Galinhas", title: "Aclimatación", highlights: ["Playa frente al pueblo", "Caminata a Praia do Cupe"], notes: "Mareas regulares — cuarto creciente", emoji: "🏖" },
    { dayNumber: 3, date: "2026-11-17", location: "Praia dos Carneiros", title: "Excursión día completo", highlights: ["Iglesia blanca icónica", "Río + palmeras + mar", "Almuerzo en la arena"], emoji: "🐢" },
    { dayNumber: 4, date: "2026-11-18", location: "Maracaípe + Pontal", title: "Snorkel y manglares", highlights: ["Praia de Maracaípe", "Pontal — desembocadura del río", "Proyecto tortugas"], emoji: "🤿" },
    { dayNumber: 5, date: "2026-11-19", location: "Muro Alto", title: "Piscina natural gigante", highlights: ["Arrecife paralelo a la costa", "Agua tibia sin olas", "Día de relax"], emoji: "🏝" },
    { dayNumber: 6, date: "2026-11-20", location: "Porto de Galinhas", title: "Día flexible", highlights: ["Segundo intento piscinas naturales si la marea ayuda", "Compras en el pueblo", "Empacar"], emoji: "🛶" },
    { dayNumber: 7, date: "2026-11-21", location: "Maragogi", title: "Traslado", highlights: ["Transfer 3h Porto → Maragogi", "Check-in", "Tarde en playa o piscina"], emoji: "🚐" },
    { dayNumber: 8, date: "2026-11-22", location: "Maragogi", title: "Mareas escalando", highlights: ["Praia de Maragogi centro o Antunes", "Reservar Tour Galés sin pagar"], notes: "Mareas ya muy buenas", emoji: "🌊" },
    { dayNumber: 9, date: "2026-11-23", location: "Praia de Antunes / Burgalhau", title: "Día previo a la supermoon", highlights: ["Antunes — la más linda", "Luna ya casi llena a la noche"], notes: "Mareas excepcionales", emoji: "🏖" },
    { dayNumber: 10, date: "2026-11-24", location: "Maragogi", title: "🌕 SUPERMOON — Tour Galés", highlights: ["1h 30min en catamarán", "Piscinas naturales gigantes a 6 km", "Snorkel entre corales expuestos", "Supermoon al atardecer sobre el mar"], notes: "Pico de marea baja del año", emoji: "🌕" },
    { dayNumber: 11, date: "2026-11-25", location: "Japaratinga / São Miguel dos Milagres", title: "Excursión al norte", highlights: ["Las 'Maldivas brasileras'", "Mareas todavía excepcionales"], emoji: "🌅" },
    { dayNumber: 12, date: "2026-11-26", location: "Maragogi", title: "Día libre — último pico de marea", highlights: ["Repetir Tour Galés a mitad de precio", "Playa al sur (Peroba)", "Hamaca en el alojamiento"], emoji: "🌊" },
    { dayNumber: 13, date: "2026-11-27", location: "Maragogi", title: "Cierre tranquilo", highlights: ["Playa", "Almuerzo de despedida", "Compras finales"], emoji: "🛍" },
    { dayNumber: 14, date: "2026-11-28", location: "Maragogi → Recife → EZE", title: "Vuelo de regreso", highlights: ["Transfer 3h a Recife", "Olinda casco histórico", "LATAM 20:25 → 01:55"], emoji: "🚐" },
    { dayNumber: 15, date: "2026-11-29", location: "Buenos Aires", title: "Llegada madrugada", highlights: ["Llegada Ezeiza 01:55", "Uber a casa, dormir"], emoji: "🏠" },
  ],

  budget: [
    { label: "Alojamiento Porto (6 noches)", minUsd: 600, maxUsd: 900 },
    { label: "Alojamiento Maragogi (7 noches)", minUsd: 600, maxUsd: 1000 },
    { label: "Transfers (3 tramos)", minUsd: 250, maxUsd: 350 },
    { label: "Tour Galés Maragogi (x2)", minUsd: 80, maxUsd: 120 },
    { label: "Excursiones (Carneiros, Antunes, etc.)", minUsd: 150, maxUsd: 250 },
    { label: "Comidas (13 días x2)", minUsd: 600, maxUsd: 900 },
    { label: "Imprevistos / souvenirs", minUsd: 200, maxUsd: 200 },
  ],

  checklist: [
    { label: "Pasaporte con +6 meses de vigencia", category: "Documentos" },
    { label: "Vacuna fiebre amarilla (recomendada)", category: "Documentos" },
    { label: "Reales en efectivo para propinas", category: "Plata" },
    { label: "Zapatillas de agua (corales)", category: "Equipo" },
    { label: "Protector solar reef-safe", category: "Equipo" },
    { label: "Snorkel propio (opcional)", category: "Equipo" },
    { label: "Repelente (Maragogi al atardecer)", category: "Equipo" },
    { label: "Adaptador de enchufe tipo N", category: "Equipo" },
    { label: "Reserva Tour Galés sin pagar (24 o 25-nov)", category: "Reservas" },
  ],

  links: [
    { label: "Tábua de Marés Maragogi", url: "https://tabuademares.com/br/alagoas/maragogi/previsao/mares", category: "Mareas" },
    { label: "Tábua de Marés Porto de Galinhas", url: "https://tabuademares.com/br/pernambuco/porto-de-galinhas/previsao/mares", category: "Mareas" },
    { label: "LATAM", url: "https://www.latam.com", category: "Vuelos" },
    { label: "JetSMART", url: "https://jetsmart.com/ar/es/", category: "Vuelos" },
    { label: "Google Flights EZE → REC", url: "https://www.google.com/travel/flights?q=Flights%20to%20REC%20from%20EZE", category: "Vuelos" },
    { label: "Calendario fases lunares 2026", url: "https://www.timeanddate.com/moon/phases/", category: "Astronomía" },
    { label: "Supermoon 24-nov-2026", url: "https://theskylive.com/full-moon-november-2026", category: "Astronomía" },
  ],
};
