// Datos prácticos de viaje (moneda, idioma, enchufes, lado de manejo, código telefónico) por país.

export type CountryFacts = {
  currency: string;     // nombre + código ISO, ej: "Real brasileño (BRL)"
  languages: string;    // idioma(s) principal(es), ej: "Portugués"
  plugTypes: string;    // tipos de enchufe, ej: "C, N"
  driveSide: "izq" | "der";  // lado de manejo
  callingCode: string;  // código telefónico, ej: "+55"
};

export const COUNTRY_FACTS: Record<string, CountryFacts> = {
  "Albania": { currency: "Lek albanés (ALL)", languages: "Albanés", plugTypes: "C, F", driveSide: "der", callingCode: "+355" },
  "Alemania": { currency: "Euro (EUR)", languages: "Alemán", plugTypes: "C, F", driveSide: "der", callingCode: "+49" },
  "Arabia Saudita": { currency: "Riyal saudí (SAR)", languages: "Árabe", plugTypes: "G", driveSide: "der", callingCode: "+966" },
  "Argentina": { currency: "Peso argentino (ARS)", languages: "Castellano", plugTypes: "C, I", driveSide: "der", callingCode: "+54" },
  "Argentina/Brasil": { currency: "Peso argentino (ARS)", languages: "Castellano", plugTypes: "C, I", driveSide: "der", callingCode: "+54" },
  "Armenia": { currency: "Dram armenio (AMD)", languages: "Armenio", plugTypes: "C, F", driveSide: "der", callingCode: "+374" },
  "Aruba": { currency: "Florín arubeño (AWG)", languages: "Neerlandés, Papiamento", plugTypes: "A, B, F", driveSide: "der", callingCode: "+297" },
  "Australia": { currency: "Dólar australiano (AUD)", languages: "Inglés", plugTypes: "I", driveSide: "izq", callingCode: "+61" },
  "Austria": { currency: "Euro (EUR)", languages: "Alemán", plugTypes: "C, F", driveSide: "der", callingCode: "+43" },
  "Azerbaiyán": { currency: "Manat azerbaiyano (AZN)", languages: "Azerí", plugTypes: "C, F", driveSide: "der", callingCode: "+994" },
  "Bahamas": { currency: "Dólar bahameño (BSD)", languages: "Inglés", plugTypes: "A, B", driveSide: "izq", callingCode: "+1" },
  "Barbados": { currency: "Dólar barbadense (BBD)", languages: "Inglés", plugTypes: "A, B", driveSide: "izq", callingCode: "+1" },
  "Baréin": { currency: "Dinar bahreiní (BHD)", languages: "Árabe", plugTypes: "G", driveSide: "der", callingCode: "+973" },
  "Bélgica": { currency: "Euro (EUR)", languages: "Neerlandés, Francés", plugTypes: "C, E", driveSide: "der", callingCode: "+32" },
  "Belice": { currency: "Dólar beliceño (BZD)", languages: "Inglés", plugTypes: "A, B, G", driveSide: "der", callingCode: "+501" },
  "Bolivia": { currency: "Boliviano (BOB)", languages: "Castellano", plugTypes: "A, C", driveSide: "der", callingCode: "+591" },
  "Bosnia y Herzegovina": { currency: "Marco convertible (BAM)", languages: "Bosnio", plugTypes: "C, F", driveSide: "der", callingCode: "+387" },
  "Botsuana": { currency: "Pula botsuano (BWP)", languages: "Inglés, Setsuana", plugTypes: "D, G, M", driveSide: "izq", callingCode: "+267" },
  "Brasil": { currency: "Real brasileño (BRL)", languages: "Portugués", plugTypes: "C, N", driveSide: "der", callingCode: "+55" },
  "Bulgaria": { currency: "Lev búlgaro (BGN)", languages: "Búlgaro", plugTypes: "C, F", driveSide: "der", callingCode: "+359" },
  "Bután": { currency: "Ngultrum (BTN)", languages: "Dzongkha", plugTypes: "C, D, G", driveSide: "izq", callingCode: "+975" },
  "Cabo Verde": { currency: "Escudo caboverdiano (CVE)", languages: "Portugués", plugTypes: "C, F", driveSide: "der", callingCode: "+238" },
  "Camboya": { currency: "Riel camboyano (KHR)", languages: "Jemer", plugTypes: "A, C, G", driveSide: "der", callingCode: "+855" },
  "Canadá": { currency: "Dólar canadiense (CAD)", languages: "Inglés, Francés", plugTypes: "A, B", driveSide: "der", callingCode: "+1" },
  "Chile": { currency: "Peso chileno (CLP)", languages: "Castellano", plugTypes: "C, L", driveSide: "der", callingCode: "+56" },
  "China": { currency: "Yuan renminbi (CNY)", languages: "Mandarín", plugTypes: "A, C, I", driveSide: "der", callingCode: "+86" },
  "Colombia": { currency: "Peso colombiano (COP)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+57" },
  "Corea del Sur": { currency: "Won surcoreano (KRW)", languages: "Coreano", plugTypes: "C, F", driveSide: "der", callingCode: "+82" },
  "Costa Rica": { currency: "Colón costarricense (CRC)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+506" },
  "Croacia": { currency: "Euro (EUR)", languages: "Croata", plugTypes: "C, F", driveSide: "der", callingCode: "+385" },
  "Cuba": { currency: "Peso cubano (CUP)", languages: "Castellano", plugTypes: "A, B, C", driveSide: "der", callingCode: "+53" },
  "Curaçao": { currency: "Florín antillano (ANG)", languages: "Neerlandés, Papiamento", plugTypes: "A, B", driveSide: "der", callingCode: "+599" },
  "Dinamarca": { currency: "Corona danesa (DKK)", languages: "Danés", plugTypes: "C, E, F, K", driveSide: "der", callingCode: "+45" },
  "Dominica": { currency: "Dólar del Caribe Oriental (XCD)", languages: "Inglés", plugTypes: "D, G", driveSide: "izq", callingCode: "+1" },
  "Ecuador": { currency: "Dólar estadounidense (USD)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+593" },
  "Egipto": { currency: "Libra egipcia (EGP)", languages: "Árabe", plugTypes: "C, F", driveSide: "der", callingCode: "+20" },
  "Emiratos Árabes Unidos": { currency: "Dírham (AED)", languages: "Árabe", plugTypes: "G", driveSide: "der", callingCode: "+971" },
  "Eslovenia": { currency: "Euro (EUR)", languages: "Esloveno", plugTypes: "C, F", driveSide: "der", callingCode: "+386" },
  "España": { currency: "Euro (EUR)", languages: "Castellano", plugTypes: "C, F", driveSide: "der", callingCode: "+34" },
  "Estados Unidos": { currency: "Dólar estadounidense (USD)", languages: "Inglés", plugTypes: "A, B", driveSide: "der", callingCode: "+1" },
  "Estonia": { currency: "Euro (EUR)", languages: "Estonio", plugTypes: "C, F", driveSide: "der", callingCode: "+372" },
  "Etiopía": { currency: "Birr etíope (ETB)", languages: "Amárico", plugTypes: "C, E, F, L", driveSide: "der", callingCode: "+251" },
  "Filipinas": { currency: "Peso filipino (PHP)", languages: "Filipino, Inglés", plugTypes: "A, B, C", driveSide: "der", callingCode: "+63" },
  "Finlandia": { currency: "Euro (EUR)", languages: "Finés", plugTypes: "C, F", driveSide: "der", callingCode: "+358" },
  "Fiyi": { currency: "Dólar fiyiano (FJD)", languages: "Inglés", plugTypes: "I", driveSide: "izq", callingCode: "+679" },
  "Francia": { currency: "Euro (EUR)", languages: "Francés", plugTypes: "C, E", driveSide: "der", callingCode: "+33" },
  "Georgia": { currency: "Lari georgiano (GEL)", languages: "Georgiano", plugTypes: "C, F", driveSide: "der", callingCode: "+995" },
  "Ghana": { currency: "Cedi ghanés (GHS)", languages: "Inglés", plugTypes: "D, G", driveSide: "der", callingCode: "+233" },
  "Granada": { currency: "Dólar del Caribe Oriental (XCD)", languages: "Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+1" },
  "Grecia": { currency: "Euro (EUR)", languages: "Griego", plugTypes: "C, F", driveSide: "der", callingCode: "+30" },
  "Guatemala": { currency: "Quetzal (GTQ)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+502" },
  "Guyana": { currency: "Dólar guyanés (GYD)", languages: "Inglés", plugTypes: "A, B, D, G", driveSide: "izq", callingCode: "+592" },
  "Honduras": { currency: "Lempira (HNL)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+504" },
  "Hungría": { currency: "Forinto húngaro (HUF)", languages: "Húngaro", plugTypes: "C, F", driveSide: "der", callingCode: "+36" },
  "India": { currency: "Rupia india (INR)", languages: "Hindi, Inglés", plugTypes: "C, D, M", driveSide: "izq", callingCode: "+91" },
  "Indonesia": { currency: "Rupia indonesia (IDR)", languages: "Indonesio", plugTypes: "C, F", driveSide: "izq", callingCode: "+62" },
  "Irán": { currency: "Rial iraní (IRR)", languages: "Persa", plugTypes: "C, F", driveSide: "der", callingCode: "+98" },
  "Irlanda": { currency: "Euro (EUR)", languages: "Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+353" },
  "Islandia": { currency: "Corona islandesa (ISK)", languages: "Islandés", plugTypes: "C, F", driveSide: "der", callingCode: "+354" },
  "Islas Cook": { currency: "Dólar neozelandés (NZD)", languages: "Inglés, Maorí cookense", plugTypes: "I", driveSide: "izq", callingCode: "+682" },
  "Israel": { currency: "Nuevo séquel (ILS)", languages: "Hebreo", plugTypes: "C, H, M", driveSide: "der", callingCode: "+972" },
  "Italia": { currency: "Euro (EUR)", languages: "Italiano", plugTypes: "C, F, L", driveSide: "der", callingCode: "+39" },
  "Jamaica": { currency: "Dólar jamaicano (JMD)", languages: "Inglés", plugTypes: "A, B", driveSide: "izq", callingCode: "+1" },
  "Japón": { currency: "Yen (JPY)", languages: "Japonés", plugTypes: "A, B", driveSide: "izq", callingCode: "+81" },
  "Jordania": { currency: "Dinar jordano (JOD)", languages: "Árabe", plugTypes: "B, C, D, F, G, J", driveSide: "der", callingCode: "+962" },
  "Kazajistán": { currency: "Tengue kazajo (KZT)", languages: "Kazajo, Ruso", plugTypes: "C, F", driveSide: "der", callingCode: "+7" },
  "Kenia": { currency: "Chelín keniano (KES)", languages: "Suajili, Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+254" },
  "Kuwait": { currency: "Dinar kuwaití (KWD)", languages: "Árabe", plugTypes: "G", driveSide: "der", callingCode: "+965" },
  "Laos": { currency: "Kip laosiano (LAK)", languages: "Lao", plugTypes: "A, B, C, E, F", driveSide: "der", callingCode: "+856" },
  "Letonia": { currency: "Euro (EUR)", languages: "Letón", plugTypes: "C, F", driveSide: "der", callingCode: "+371" },
  "Líbano": { currency: "Libra libanesa (LBP)", languages: "Árabe", plugTypes: "A, B, C, D, G", driveSide: "der", callingCode: "+961" },
  "Lituania": { currency: "Euro (EUR)", languages: "Lituano", plugTypes: "C, F", driveSide: "der", callingCode: "+370" },
  "Madagascar": { currency: "Ariary malgache (MGA)", languages: "Malgache, Francés", plugTypes: "C, D, E, J, K", driveSide: "der", callingCode: "+261" },
  "Malasia": { currency: "Ringgit malayo (MYR)", languages: "Malayo", plugTypes: "G", driveSide: "izq", callingCode: "+60" },
  "Maldivas": { currency: "Rufiyaa (MVR)", languages: "Dhivehi", plugTypes: "D, G", driveSide: "izq", callingCode: "+960" },
  "Malta": { currency: "Euro (EUR)", languages: "Maltés, Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+356" },
  "Marruecos": { currency: "Dírham marroquí (MAD)", languages: "Árabe", plugTypes: "C, E", driveSide: "der", callingCode: "+212" },
  "Mauricio": { currency: "Rupia mauriciana (MUR)", languages: "Inglés, Francés", plugTypes: "C, G", driveSide: "izq", callingCode: "+230" },
  "México": { currency: "Peso mexicano (MXN)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+52" },
  "Mónaco": { currency: "Euro (EUR)", languages: "Francés", plugTypes: "C, E, F", driveSide: "der", callingCode: "+377" },
  "Mongolia": { currency: "Tugrik (MNT)", languages: "Mongol", plugTypes: "C, E", driveSide: "der", callingCode: "+976" },
  "Montenegro": { currency: "Euro (EUR)", languages: "Montenegrino", plugTypes: "C, F", driveSide: "der", callingCode: "+382" },
  "Mozambique": { currency: "Metical (MZN)", languages: "Portugués", plugTypes: "C, F, M", driveSide: "izq", callingCode: "+258" },
  "Myanmar": { currency: "Kyat (MMK)", languages: "Birmano", plugTypes: "C, D, F, G", driveSide: "der", callingCode: "+95" },
  "Namibia": { currency: "Dólar namibio (NAD)", languages: "Inglés", plugTypes: "D, M", driveSide: "izq", callingCode: "+264" },
  "Nepal": { currency: "Rupia nepalí (NPR)", languages: "Nepalí", plugTypes: "C, D, M", driveSide: "izq", callingCode: "+977" },
  "Nicaragua": { currency: "Córdoba (NIO)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+505" },
  "Noruega": { currency: "Corona noruega (NOK)", languages: "Noruego", plugTypes: "C, F", driveSide: "der", callingCode: "+47" },
  "Nueva Zelanda": { currency: "Dólar neozelandés (NZD)", languages: "Inglés", plugTypes: "I", driveSide: "izq", callingCode: "+64" },
  "Omán": { currency: "Rial omaní (OMR)", languages: "Árabe", plugTypes: "G", driveSide: "der", callingCode: "+968" },
  "Países Bajos": { currency: "Euro (EUR)", languages: "Neerlandés", plugTypes: "C, F", driveSide: "der", callingCode: "+31" },
  "Palaos": { currency: "Dólar estadounidense (USD)", languages: "Palauano, Inglés", plugTypes: "A, B", driveSide: "der", callingCode: "+680" },
  "Panamá": { currency: "Balboa (PAB), Dólar estadounidense (USD)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+507" },
  "Paraguay": { currency: "Guaraní (PYG)", languages: "Castellano, Guaraní", plugTypes: "C", driveSide: "der", callingCode: "+595" },
  "Perú": { currency: "Sol (PEN)", languages: "Castellano", plugTypes: "A, B, C", driveSide: "der", callingCode: "+51" },
  "Polinesia Francesa": { currency: "Franco CFP (XPF)", languages: "Francés", plugTypes: "C, E", driveSide: "der", callingCode: "+689" },
  "Polonia": { currency: "Zloty (PLN)", languages: "Polaco", plugTypes: "C, E", driveSide: "der", callingCode: "+48" },
  "Portugal": { currency: "Euro (EUR)", languages: "Portugués", plugTypes: "C, F", driveSide: "der", callingCode: "+351" },
  "Puerto Rico": { currency: "Dólar estadounidense (USD)", languages: "Castellano, Inglés", plugTypes: "A, B", driveSide: "der", callingCode: "+1" },
  "Qatar": { currency: "Riyal catarí (QAR)", languages: "Árabe", plugTypes: "D, G", driveSide: "der", callingCode: "+974" },
  "Reino Unido": { currency: "Libra esterlina (GBP)", languages: "Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+44" },
  "República Checa": { currency: "Corona checa (CZK)", languages: "Checo", plugTypes: "C, E", driveSide: "der", callingCode: "+420" },
  "República Dominicana": { currency: "Peso dominicano (DOP)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+1" },
  "Ruanda": { currency: "Franco ruandés (RWF)", languages: "Kinyaruanda, Inglés", plugTypes: "C, J", driveSide: "der", callingCode: "+250" },
  "Rumania": { currency: "Leu rumano (RON)", languages: "Rumano", plugTypes: "C, F", driveSide: "der", callingCode: "+40" },
  "Rusia": { currency: "Rublo ruso (RUB)", languages: "Ruso", plugTypes: "C, F", driveSide: "der", callingCode: "+7" },
  "Samoa": { currency: "Tala samoano (WST)", languages: "Samoano, Inglés", plugTypes: "I", driveSide: "izq", callingCode: "+685" },
  "Santa Lucía": { currency: "Dólar del Caribe Oriental (XCD)", languages: "Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+1" },
  "Senegal": { currency: "Franco CFA (XOF)", languages: "Francés", plugTypes: "C, D, E, K", driveSide: "der", callingCode: "+221" },
  "Serbia": { currency: "Dinar serbio (RSD)", languages: "Serbio", plugTypes: "C, F", driveSide: "der", callingCode: "+381" },
  "Seychelles": { currency: "Rupia seychelense (SCR)", languages: "Inglés, Francés, Criollo", plugTypes: "G", driveSide: "izq", callingCode: "+248" },
  "Singapur": { currency: "Dólar de Singapur (SGD)", languages: "Inglés", plugTypes: "G", driveSide: "izq", callingCode: "+65" },
  "Sri Lanka": { currency: "Rupia de Sri Lanka (LKR)", languages: "Cingalés, Tamil", plugTypes: "D, G, M", driveSide: "izq", callingCode: "+94" },
  "Sudáfrica": { currency: "Rand (ZAR)", languages: "Inglés", plugTypes: "C, D, M, N", driveSide: "izq", callingCode: "+27" },
  "Suecia": { currency: "Corona sueca (SEK)", languages: "Sueco", plugTypes: "C, F", driveSide: "der", callingCode: "+46" },
  "Suiza": { currency: "Franco suizo (CHF)", languages: "Alemán, Francés, Italiano", plugTypes: "C, J", driveSide: "der", callingCode: "+41" },
  "Tailandia": { currency: "Baht (THB)", languages: "Tailandés", plugTypes: "A, B, C, O", driveSide: "izq", callingCode: "+66" },
  "Taiwán": { currency: "Nuevo dólar taiwanés (TWD)", languages: "Mandarín", plugTypes: "A, B", driveSide: "der", callingCode: "+886" },
  "Tanzania": { currency: "Chelín tanzano (TZS)", languages: "Suajili, Inglés", plugTypes: "D, G", driveSide: "izq", callingCode: "+255" },
  "Túnez": { currency: "Dinar tunecino (TND)", languages: "Árabe", plugTypes: "C, E", driveSide: "der", callingCode: "+216" },
  "Turks & Caicos": { currency: "Dólar estadounidense (USD)", languages: "Inglés", plugTypes: "A, B", driveSide: "izq", callingCode: "+1" },
  "Turquía": { currency: "Lira turca (TRY)", languages: "Turco", plugTypes: "C, F", driveSide: "der", callingCode: "+90" },
  "Uganda": { currency: "Chelín ugandés (UGX)", languages: "Inglés, Suajili", plugTypes: "G", driveSide: "izq", callingCode: "+256" },
  "Uruguay": { currency: "Peso uruguayo (UYU)", languages: "Castellano", plugTypes: "C, F, I, L", driveSide: "der", callingCode: "+598" },
  "Uzbekistán": { currency: "Som uzbeko (UZS)", languages: "Uzbeko", plugTypes: "C, F", driveSide: "der", callingCode: "+998" },
  "Vanuatu": { currency: "Vatu (VUV)", languages: "Bislama, Inglés, Francés", plugTypes: "I", driveSide: "der", callingCode: "+678" },
  "Venezuela": { currency: "Bolívar (VES)", languages: "Castellano", plugTypes: "A, B", driveSide: "der", callingCode: "+58" },
  "Vietnam": { currency: "Dong (VND)", languages: "Vietnamita", plugTypes: "A, C, F", driveSide: "der", callingCode: "+84" },
  "Zimbabue / Zambia": { currency: "Kwacha zambiano (ZMW)", languages: "Inglés", plugTypes: "C, D, G", driveSide: "izq", callingCode: "+260" },
};
